### PR TITLE
Fix for Plots display issues

### PR DESCRIPTION
**Pull request by tbreloff**
added check for OVERRIDE_PYPLOT_DISPLAY; fixes Plots display issues

### CODE REVIEW

**Comment by stevengj** [comment]
I don't understand the need for this; why not just set `PyPlot.is_ijulia_display[1] = false`?

Note that you will problably want to use some kind of finalizer in Plots, similar to my finalizer in the `withfig` function, to make sure that the figure closes.

**Comment by tbreloff** [comment]
At first I just set it to false, but then it didn't use the value when
setting up the gui, and so I couldn't open a gui window from IJulia on a
call to 'Plots.gui()'. So I needed a way to set it to false before PyPlot
initialization, and this is the only method I could think of to accomplish
that.

Thanks for the finalizer tip.

**Comment by tbreloff** [comment]
Is there a chance you'd merge this, or should I attempt to hack together another solution?  Thanks!

**Comment by stevengj** [comment]
Hi, sorry I let this fall off the queue while I was traveling.

I'm still not entirely sure what problem you are trying to solve here.   If you want to switch to the gui, why not call `pygui(true)`?

**Comment by stevengj** [comment]
Note that if you really need it to ignore `IJulia` and other displays during `__init__`, you can do it without patching PyPlot via the following hack (that causes `displayok()` to return false);
```jl
let otherdisplays = splice!(Base.Multimedia.displays, 2:length(Base.Multimedia.displays))
   import PyPlot
   append(Base.Multimedia.displays, otherdisplays)
end
```

**Comment by tbreloff** [comment]
@stevengj Thanks!!  This is precisely the sort of hack I needed, and it works perfectly. :100: 

The issue wasn't that I wanted to switch to gui... it's that I wanted to maintain full control over the displaying.  Now I can show (or not) inline or to the gui window, in any combination.  Thanks!

**Comment by tbreloff** [comment]
Also... I was bummed that we didn't get a chance to meet up at JuliaCon... hopefully next year @stevengj

**Comment by stevengj** [comment]
Yup, I was in Scotland that week.  But New York isn't far from Boston, so let me know if you are ever in town.

**Pull request closed without merging**
