### PR TITLE
Add support for the GR backend

### PR DESCRIPTION
**Pull request by jheinen**
See discussion _"Need help with GR and PyPlot"_ in Google group ``julia-users`` (https://groups.google.com/forum/#!topic/julia-users/0P68pflAxmM)

### CODE REVIEW

**Comment by stevengj** [comment]
We already look at the `MPLBACKEND` environment variable here: https://github.com/stevengj/PyPlot.jl/blob/a1171171f0a356172cd3e51a36872018007b365c/src/PyPlot.jl#L139-L140

The problem with doing it this way is that you aren't starting an event loop, so interactive mode won't work.  (`show()` will be blocking.)

The issue is that the GR backend is not one of the recognized backends in `find_backend`.    To make it a recognized backend, you just need to figure out what event loop (wx, qt, ...?) it needs.

**Comment by jheinen** [comment]
Is the last commit (b933fd6) acceptable? I think it will not affect any other backend.

If GR is operating in interactive mode there is no need for an event loop. If GR shall be used from within Qt, wxWidgets, Gtk or OpenGL based GUIs, it can be embedded into the corresponding event loop using the GKS connection identifier, e.g. by means of a window handle. This makes it possible to "mix" 2D and 3D graphics ...

**Comment by stevengj** [comment]
Why is there no need for an event loop for GR in interactive mode.  What process handles mouse clicks etc?

**Comment by jheinen** [comment]
GR has its "own" native graphics drivers for Linux, OS X and Windows and will handle display updates using threads. The focus is interoperability and the display of continuous data streams (at any time, triggered by an application). User interaction (= interactivity) is managed by the OS window manager - but, in this case, the user should always be the master. The latter can be implemented much more efficient using API functions of GUI toolkits than with methods provided by any graphics backends.

BTW: We are preparing a Qt based "standalone" GR backend which will allow both the Matplotlib-like behaviour but also provide "live" displays. I can't estimate when this backend will be finished. But I'd really appreciate if you could merge the PR although there seem to be different opinions about (object-oriented) event-driven apps and imperative programmed apps. I'm sure we can close this gap with the new backend ASAP.

**Comment by stevengj** [comment]
So GR spawns its own thread to do the event loop?  I'm fine with that, but in that case this PR is still incorrect, because setting the GUI as `:none` will cause PyPlot to load matplotlib in non-interactive mode.  Probably you should set the GUI to `:gr` or something like that, and add another `if` branch for that down where the `g == :none` is.

(Also, does GR work with `pyplot.switch_backend("Agg")` for switching to inline plotting in IJulia?)

**Comment by jheinen** [comment]
Is there a chance that b933fd6 can be merged? I not, I could not understand and I don't know how to explain it to users ...

**Comment by jheinen** [comment]
There is no need to switch to another backend for inline plotting in Jupyter. GR will produce inline graphics (SVG, PNG, PDF or JS), even if called from Matplotlib, both for Python and Julia. I can re-check the PyPlot logic (GUI vs. interactive modes), although I did not see a problem during some basic tests - so there should not be any further work for you.

**Comment by jheinen** [comment]
With the latest commit (5071be4) I added a ``:gr`` GUI and an ``if g == :gr`` branch for future extensions (currently not needed). For inline plotting in IJulia with GR, it's important **NOT** to invoke the ``monkeypatch()``.

With this patch, all our apps are running again (both in interactive, GUI or notebook environments).

**Comment by stevengj** [comment]
In a Jupyter inline-plotting environment, when you type `plot`, the plot should only appear in the browser, not also in a separate window.  That's why we switch to the `Agg` backend.   By disabling this, it sounds like you have it set up so that the separate window still appears even when you are doing inline plotting?

**Comment by stevengj** [comment]
(PS. I will be happy to merge this once all questions/objections are resolved.  But getting to that point requires a little patience and discussion; repeatedly asking me to merge is not helpful.)

**Comment by jheinen** [comment]
> In a Jupyter inline-plotting environment, when you type plot, the plot should only appear in the browser, not also in a separate window. That's why we switch to the Agg backend. By disabling this, it sounds like you have it set up so that the separate plot window still appears even when you are doing inline plotting?

The plot only appears in the browser. GR will produce SVG or PNG output, whatever the user prefers. This can be set using ``GR.inline("svg|png|mov|js")``

**Comment by stevengj** [comment]
@jheinen, how does it know to pop up a separate plot window when you run, say, `figure()` from the REPL, but not when you run from IJulia?  Is the monkey-patched `draw_if_interactive` enough for the GR backend not to pop up windows for `isjulia_display[1] == true`?

**Comment by stevengj** [comment]
If it working fine from both the REPL and IJulia, without popping up windows in the later, then I can merge this once you do a rebase to squash the PR into a single commit.

**Comment by stevengj** [comment]
In general, the right thing is to do a forced push to update this PR. That way, the merge commit will be linked on Github to this PR where the discussion took place.

**Comment by stevengj** [comment]
(I just noticed that github now offers a "squash and merge" option, so you no longer have to manually squash.)

**Pull request closed without merging**
