### PR TITLE
Allow selection of the Matplotlib backend using the MPLBACKEND enviro…

### PR DESCRIPTION
**Pull request by jheinen**
This patch allows setting the Matplotlib backend without changing the users' scripts or customizing default options (in .matplotlibrc). This feature is especially useful when mixing (existing) PyPlot calls with functions provided by the [GR framework](http://gr-framework.org/tutorials/matplotlib.html), a universal framework for cross-platform visualization applications.

A similar [pull request](https://github.com/matplotlib/matplotlib/pull/3710) (for Matplotlib) has already been accepted by the MPL developers. [Here](http://gr-framework.org/tutorials/mpl_interop.html) you can find a Python example which can easily be ported to Julia, providing enhanced features, especially for real-time visualization.

This is how a Julia example would look like:

    import PyCall
    @PyCall.pyimport numpy as np
 
    import PyPlot
    mpl = PyPlot
 
    import GR
 
    angles = np.load("700K_460.npy")
    lens = []
 
    for t in 1:100 
        mpl.cla()
        fig = mpl.subplot(211)
        mpl.ylim([0, 1000])
        mpl.hist(angles[t], 20, normed=0, facecolor="g", alpha=0.5)
        mpl.show()
 
        lens = [lens, np.size(angles[t])]
        if t > 1
            GR.setwindow(0, 10, 3500, 5000)
            GR.setviewport(0.1, 0.9, 0.05, 0.4)
            GR.axes(1, 0, 0, 3500, 2, 0, 0.005)
            GR.polyline(np.arange(t) / 10.0, lens)
        end
 
        GR.updatews()
    end

### CODE REVIEW

**Comment by stevengj** [comment]
This is the wrong place to put it — you need to modify the `find_backend` function so that another backend does not get initialized.

**Comment by jheinen** [comment]
I understand. I changed the logic in the last commit (0321c0d). The ``find_backend`` function is no longer called when the ``MPLBACKEND`` environment is set. The user should be able to switch the backend without changing a single line of code. Is this ok?

**Comment by stevengj** [comment]
No, you still need `find_backend`.   For one thing, the `MPLBACKEND` might not be supported.  For another thing, `find_backend` figures out whether we need to start a GUI event-loop thread for the backend.

Basically, I think you should just alter/extend the `default = lowercase(get(rcParams, "backend", "none"))` line.

Question:  if you have both `MPLBACKEND` and a backend specified in your matplotlibrc, which takes precedence?

**Comment by stevengj** [comment]
Ah, I see the docs say: `Setting this environment variable will override the ``backend`` parameter
in *any* ``matplotlibrc``, even if there is a ``matplotlibrc`` in your current working directory.`

**Comment by stevengj** [comment]
Implemented in 70ea59bf85eecccb4626b59a5163718437fad374

**Comment by jheinen** [comment]
Checked out PyPlot.jl master branch - works perfect.
Thanks!

**Pull request closed without merging**
